### ISSUE TITLE
Convert HTML site to use Gatsby.js

### ISSUE THREAD

**Issue by mcastre** [mcastre/phantom-phlashers#1]
I would normally do this myself but I have been fairly busy with work stuff, so I thought I'd open this up to the open-source community for help!

**Requirements:**
- Convert website to use Gatsby.js core
- Normal functionality of the website should not change
- Can use a starter Gatsby project. If so, please make sure you are using one that includes Babel, latest React version, and SCSS (no UI frameworks please!). No need for Typescript or anything since this is a small project.

This is a feature request!

**Comment by nindyahapsari** [comment]
Hi, may I help with this one?

**Comment by mcastre** [comment]
Of course! Thank you!

**Comment by mcastre** [comment]
@nindyahapsari i assigned the issue to you.

**Comment by nindyahapsari** [comment]
Hi, I'm sorry that I reply pretty late. I am wondering if you can help me with some small issue. I actually done converting the files to gatsby. But It seems that I couldn't make the swipebox jquery to work in react. Do you have any idea how can I solve this one?

**Comment by mcastre** [comment]
That's great! Yea, most likely I'll have to use a photo gallery specifically for react. You don't have to worry about that, since we want to avoid using jQuery in a react app. I can use something else for that. 

Or, if you want, you could open up a separate PR for replacing the swipebox plugin with a react mom package?

**Comment by nindyahapsari** [comment]
Oh ok, in that case, I can make the first pull request and then make another separate PR for the photo gallery. If that's alright.

**Comment by mcastre** [comment]
Yea that sounds good!
